

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    depends_on:
      - db
    command: flask run --host=0.0.0.0

  db:
    image: sqlite:3.38.5-alpine
    volumes:
      - db_data:/var/lib/sqlite

volumes:
  db_data: